import Head from 'next/head'
import { makeStyles } from '@material-ui/core/styles';
import Table from '@material-ui/core/Table';
import TableBody from '@material-ui/core/TableBody';
import TableCell from '@material-ui/core/TableCell';
import TableContainer from '@material-ui/core/TableContainer';
import TableHead from '@material-ui/core/TableHead';
import TableRow from '@material-ui/core/TableRow';
import Paper from '@material-ui/core/Paper';
import CssBaseline from '@material-ui/core/CssBaseline';
import Typography from '@material-ui/core/Typography';
import Container from '@material-ui/core/Container';



const useStyles = makeStyles({
  table: {
    minWidth: 450,
  },
});


export default function Home({dados}) {

  const classes = useStyles();


  return (
    <div>
      <Head>
        <title>OrangePi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CssBaseline />
      <Container maxWidth="sm">
        <Typography component="div" style={{ backgroundColor: '#cfe8fc', height: '100vh' }}>
     


      <TableContainer component={Paper}>
      <Table className={classes.table} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell>Host</TableCell>
            <TableCell align="right">Data</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {dados.map((row) => (
            <TableRow key={row.host}>
              <TableCell component="th" scope="row">
                {row.host}
              </TableCell>
              <TableCell align="right">{row.data}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>

    </Typography>
    </Container>
     
    </div>
  )
}



export const getStaticProps = async () => {
  const res = await fetch('https://keyh4.herokuapp.com/Bibaiysdioashdus');
  const data = await res.json();
  
  return {
    props: {
      dados: data,
    },
    revalidate: 60
  }
};